# Para todos as constantes considere ACERTOU a frente da palavra, menos o ERRO_TUDO

PONTOS_PLACAR = 7
PONTOS_VENCEDOR_RESULTADO_GOLS_UM_TIME = 5
PONTOS_VENCEDOR = 4
PONTOS_EMPATE_PLACAR_INCORRETO = 3
PONTOS_SOMENTE_RESULTADO_GOLS_UM_TIME = 2
PONTOS_ERRO = 0
