# -*- encoding: utf-8 -*-

# Para todos as constantes considere ACERTOU a frente da palavra, menos o ERRO_TUDO
PONTOS_PLACAR = 6
PONTOS_VENCEDOR_RESULTADO_GOLS_UM_TIME = 4
PONTOS_VENCEDOR = 3
PONTOS_EMPATE_PLACAR_INCORRETO = 3
PONTOS_SOMENTE_RESULTADO_GOLS_UM_TIME = 1
PONTOS_ERRO = 0

STATUS_CODIGO_EDICAO = 'E'
STATUS_CODIGO_ANDAMENTO = 'A'
STATUS_CODIGO_FINALIZADO = 'F'
