# Para todos as constantes considere ACERTOU a frente da palavra, menos o ERRO_TUDO

PLACAR = 7
#VENCEDOR_QTDE_GOLS_DE_UM_TIME = 5
VENCEDOR = 4
EMPATE_SEM_PLACAR_CORRETO = 3
#SOMENTE_UM_TIME_EM_QTDE_GOLS = 2
ERRO_TUDO = 0
